; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

define i16 @bare_select(i1 %a, i16 %b, i16 %c) {
; RV16K-LABEL: bare_select:
; RV16K:       # %bb.0:
; RV16K-NEXT:	li	a3, 1
; RV16K-NEXT:	and	a3, a0
; RV16K-NEXT:	cmpi	a3, 0
; RV16K-NEXT:	jne	.LBB0_2
; RV16K-NEXT:# %bb.1:
; RV16K-NEXT:	mov	a1, a2
; RV16K-NEXT:.LBB0_2:
; RV16K-NEXT:	mov	a0, a1
; RV16K-NEXT:	jr	ra

  %1 = select i1 %a, i16 %b, i16 %c
  ret i16 %1
}
