; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

; FIXME: This test should be much simpler when inline assembly enabled.

define i16 @test(i16 %a, i16 %b) {
; RV16K-LABEL: test:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -4
; RV16K-NEXT:	swsp	a1, 0(sp)
; RV16K-NEXT:	swsp	a0, 2(sp)
; RV16K-NEXT:	cmp	a0, a1
; RV16K-NEXT:	jl	.LBB0_1
; RV16K-NEXT:	j	.LBB0_2
; RV16K-NEXT:.LBB0_1:
; RV16K-NEXT:	lwsp	a0, 0(sp)
; RV16K-NEXT:	lwsp	a1, 2(sp)
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	swsp	a1, 2(sp)
; RV16K-NEXT:.LBB0_2:
; RV16K-NEXT:	lwsp	a0, 2(sp)
; RV16K-NEXT:	addi	sp, 4
; RV16K-NEXT:	jr	ra

entry:
  %a.addr = alloca i16
  %b.addr = alloca i16
  store i16 %a, i16* %a.addr
  store i16 %b, i16* %b.addr
  %0 = load i16, i16* %a.addr
  %1 = load i16, i16* %b.addr
  %cmp = icmp slt i16 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:
  %2 = load i16, i16* %b.addr
  %3 = load i16, i16* %a.addr
  %add = add nsw i16 %3, %2
  store i16 %add, i16* %a.addr
  %4 = load i16, i16* %b.addr
  %5 = load i16, i16* %a.addr
  %add1 = add nsw i16 %5, %4
  store i16 %add1, i16* %a.addr
  %6 = load i16, i16* %b.addr
  %7 = load i16, i16* %a.addr
  %add2 = add nsw i16 %7, %6
  store i16 %add2, i16* %a.addr
  %8 = load i16, i16* %b.addr
  %9 = load i16, i16* %a.addr
  %add3 = add nsw i16 %9, %8
  store i16 %add3, i16* %a.addr
  %10 = load i16, i16* %b.addr
  %11 = load i16, i16* %a.addr
  %add4 = add nsw i16 %11, %10
  store i16 %add4, i16* %a.addr
  %12 = load i16, i16* %b.addr
  %13 = load i16, i16* %a.addr
  %add5 = add nsw i16 %13, %12
  store i16 %add5, i16* %a.addr
  %14 = load i16, i16* %b.addr
  %15 = load i16, i16* %a.addr
  %add6 = add nsw i16 %15, %14
  store i16 %add6, i16* %a.addr
  %16 = load i16, i16* %b.addr
  %17 = load i16, i16* %a.addr
  %add7 = add nsw i16 %17, %16
  store i16 %add7, i16* %a.addr
  %18 = load i16, i16* %b.addr
  %19 = load i16, i16* %a.addr
  %add8 = add nsw i16 %19, %18
  store i16 %add8, i16* %a.addr
  %20 = load i16, i16* %b.addr
  %21 = load i16, i16* %a.addr
  %add9 = add nsw i16 %21, %20
  store i16 %add9, i16* %a.addr
  %22 = load i16, i16* %b.addr
  %23 = load i16, i16* %a.addr
  %add10 = add nsw i16 %23, %22
  store i16 %add10, i16* %a.addr
  %24 = load i16, i16* %b.addr
  %25 = load i16, i16* %a.addr
  %add11 = add nsw i16 %25, %24
  store i16 %add11, i16* %a.addr
  %26 = load i16, i16* %b.addr
  %27 = load i16, i16* %a.addr
  %add12 = add nsw i16 %27, %26
  store i16 %add12, i16* %a.addr
  %28 = load i16, i16* %b.addr
  %29 = load i16, i16* %a.addr
  %add13 = add nsw i16 %29, %28
  store i16 %add13, i16* %a.addr
  %30 = load i16, i16* %b.addr
  %31 = load i16, i16* %a.addr
  %add14 = add nsw i16 %31, %30
  store i16 %add14, i16* %a.addr
  %32 = load i16, i16* %b.addr
  %33 = load i16, i16* %a.addr
  %add15 = add nsw i16 %33, %32
  store i16 %add15, i16* %a.addr
  %34 = load i16, i16* %b.addr
  %35 = load i16, i16* %a.addr
  %add16 = add nsw i16 %35, %34
  store i16 %add16, i16* %a.addr
  %36 = load i16, i16* %b.addr
  %37 = load i16, i16* %a.addr
  %add17 = add nsw i16 %37, %36
  store i16 %add17, i16* %a.addr
  %38 = load i16, i16* %b.addr
  %39 = load i16, i16* %a.addr
  %add18 = add nsw i16 %39, %38
  store i16 %add18, i16* %a.addr
  %40 = load i16, i16* %b.addr
  %41 = load i16, i16* %a.addr
  %add19 = add nsw i16 %41, %40
  store i16 %add19, i16* %a.addr
  %42 = load i16, i16* %b.addr
  %43 = load i16, i16* %a.addr
  %add20 = add nsw i16 %43, %42
  store i16 %add20, i16* %a.addr
  %44 = load i16, i16* %b.addr
  %45 = load i16, i16* %a.addr
  %add21 = add nsw i16 %45, %44
  store i16 %add21, i16* %a.addr
  %46 = load i16, i16* %b.addr
  %47 = load i16, i16* %a.addr
  %add22 = add nsw i16 %47, %46
  store i16 %add22, i16* %a.addr
  %48 = load i16, i16* %b.addr
  %49 = load i16, i16* %a.addr
  %add23 = add nsw i16 %49, %48
  store i16 %add23, i16* %a.addr
  %50 = load i16, i16* %b.addr
  %51 = load i16, i16* %a.addr
  %add24 = add nsw i16 %51, %50
  store i16 %add24, i16* %a.addr
  %52 = load i16, i16* %b.addr
  %53 = load i16, i16* %a.addr
  %add25 = add nsw i16 %53, %52
  store i16 %add25, i16* %a.addr
  %54 = load i16, i16* %b.addr
  %55 = load i16, i16* %a.addr
  %add26 = add nsw i16 %55, %54
  store i16 %add26, i16* %a.addr
  %56 = load i16, i16* %b.addr
  %57 = load i16, i16* %a.addr
  %add27 = add nsw i16 %57, %56
  store i16 %add27, i16* %a.addr
  %58 = load i16, i16* %b.addr
  %59 = load i16, i16* %a.addr
  %add28 = add nsw i16 %59, %58
  store i16 %add28, i16* %a.addr
  %60 = load i16, i16* %b.addr
  %61 = load i16, i16* %a.addr
  %add29 = add nsw i16 %61, %60
  store i16 %add29, i16* %a.addr
  %62 = load i16, i16* %b.addr
  %63 = load i16, i16* %a.addr
  %add30 = add nsw i16 %63, %62
  store i16 %add30, i16* %a.addr
  %64 = load i16, i16* %b.addr
  %65 = load i16, i16* %a.addr
  %add31 = add nsw i16 %65, %64
  store i16 %add31, i16* %a.addr
  %66 = load i16, i16* %b.addr
  %67 = load i16, i16* %a.addr
  %add32 = add nsw i16 %67, %66
  store i16 %add32, i16* %a.addr
  %68 = load i16, i16* %b.addr
  %69 = load i16, i16* %a.addr
  %add33 = add nsw i16 %69, %68
  store i16 %add33, i16* %a.addr
  %70 = load i16, i16* %b.addr
  %71 = load i16, i16* %a.addr
  %add34 = add nsw i16 %71, %70
  store i16 %add34, i16* %a.addr
  %72 = load i16, i16* %b.addr
  %73 = load i16, i16* %a.addr
  %add35 = add nsw i16 %73, %72
  store i16 %add35, i16* %a.addr
  %74 = load i16, i16* %b.addr
  %75 = load i16, i16* %a.addr
  %add36 = add nsw i16 %75, %74
  store i16 %add36, i16* %a.addr
  %76 = load i16, i16* %b.addr
  %77 = load i16, i16* %a.addr
  %add37 = add nsw i16 %77, %76
  store i16 %add37, i16* %a.addr
  %78 = load i16, i16* %b.addr
  %79 = load i16, i16* %a.addr
  %add38 = add nsw i16 %79, %78
  store i16 %add38, i16* %a.addr
  %80 = load i16, i16* %b.addr
  %81 = load i16, i16* %a.addr
  %add39 = add nsw i16 %81, %80
  store i16 %add39, i16* %a.addr
  %82 = load i16, i16* %b.addr
  %83 = load i16, i16* %a.addr
  %add40 = add nsw i16 %83, %82
  store i16 %add40, i16* %a.addr
  %84 = load i16, i16* %b.addr
  %85 = load i16, i16* %a.addr
  %add41 = add nsw i16 %85, %84
  store i16 %add41, i16* %a.addr
  %86 = load i16, i16* %b.addr
  %87 = load i16, i16* %a.addr
  %add42 = add nsw i16 %87, %86
  store i16 %add42, i16* %a.addr
  %88 = load i16, i16* %b.addr
  %89 = load i16, i16* %a.addr
  %add43 = add nsw i16 %89, %88
  store i16 %add43, i16* %a.addr
  %90 = load i16, i16* %b.addr
  %91 = load i16, i16* %a.addr
  %add44 = add nsw i16 %91, %90
  store i16 %add44, i16* %a.addr
  %92 = load i16, i16* %b.addr
  %93 = load i16, i16* %a.addr
  %add45 = add nsw i16 %93, %92
  store i16 %add45, i16* %a.addr
  %94 = load i16, i16* %b.addr
  %95 = load i16, i16* %a.addr
  %add46 = add nsw i16 %95, %94
  store i16 %add46, i16* %a.addr
  %96 = load i16, i16* %b.addr
  %97 = load i16, i16* %a.addr
  %add47 = add nsw i16 %97, %96
  store i16 %add47, i16* %a.addr
  %98 = load i16, i16* %b.addr
  %99 = load i16, i16* %a.addr
  %add48 = add nsw i16 %99, %98
  store i16 %add48, i16* %a.addr
  %100 = load i16, i16* %b.addr
  %101 = load i16, i16* %a.addr
  %add49 = add nsw i16 %101, %100
  store i16 %add49, i16* %a.addr
  %102 = load i16, i16* %b.addr
  %103 = load i16, i16* %a.addr
  %add50 = add nsw i16 %103, %102
  store i16 %add50, i16* %a.addr
  %104 = load i16, i16* %b.addr
  %105 = load i16, i16* %a.addr
  %add51 = add nsw i16 %105, %104
  store i16 %add51, i16* %a.addr
  %106 = load i16, i16* %b.addr
  %107 = load i16, i16* %a.addr
  %add52 = add nsw i16 %107, %106
  store i16 %add52, i16* %a.addr
  %108 = load i16, i16* %b.addr
  %109 = load i16, i16* %a.addr
  %add53 = add nsw i16 %109, %108
  store i16 %add53, i16* %a.addr
  %110 = load i16, i16* %b.addr
  %111 = load i16, i16* %a.addr
  %add54 = add nsw i16 %111, %110
  store i16 %add54, i16* %a.addr
  %112 = load i16, i16* %b.addr
  %113 = load i16, i16* %a.addr
  %add55 = add nsw i16 %113, %112
  store i16 %add55, i16* %a.addr
  %114 = load i16, i16* %b.addr
  %115 = load i16, i16* %a.addr
  %add56 = add nsw i16 %115, %114
  store i16 %add56, i16* %a.addr
  %116 = load i16, i16* %b.addr
  %117 = load i16, i16* %a.addr
  %add57 = add nsw i16 %117, %116
  store i16 %add57, i16* %a.addr
  %118 = load i16, i16* %b.addr
  %119 = load i16, i16* %a.addr
  %add58 = add nsw i16 %119, %118
  store i16 %add58, i16* %a.addr
  %120 = load i16, i16* %b.addr
  %121 = load i16, i16* %a.addr
  %add59 = add nsw i16 %121, %120
  store i16 %add59, i16* %a.addr
  %122 = load i16, i16* %b.addr
  %123 = load i16, i16* %a.addr
  %add60 = add nsw i16 %123, %122
  store i16 %add60, i16* %a.addr
  %124 = load i16, i16* %b.addr
  %125 = load i16, i16* %a.addr
  %add61 = add nsw i16 %125, %124
  store i16 %add61, i16* %a.addr
  %126 = load i16, i16* %b.addr
  %127 = load i16, i16* %a.addr
  %add62 = add nsw i16 %127, %126
  store i16 %add62, i16* %a.addr
  %128 = load i16, i16* %b.addr
  %129 = load i16, i16* %a.addr
  %add63 = add nsw i16 %129, %128
  store i16 %add63, i16* %a.addr
  %130 = load i16, i16* %b.addr
  %131 = load i16, i16* %a.addr
  %add64 = add nsw i16 %131, %130
  store i16 %add64, i16* %a.addr
  %132 = load i16, i16* %b.addr
  %133 = load i16, i16* %a.addr
  %add65 = add nsw i16 %133, %132
  store i16 %add65, i16* %a.addr
  %134 = load i16, i16* %b.addr
  %135 = load i16, i16* %a.addr
  %add66 = add nsw i16 %135, %134
  store i16 %add66, i16* %a.addr
  %136 = load i16, i16* %b.addr
  %137 = load i16, i16* %a.addr
  %add67 = add nsw i16 %137, %136
  store i16 %add67, i16* %a.addr
  %138 = load i16, i16* %b.addr
  %139 = load i16, i16* %a.addr
  %add68 = add nsw i16 %139, %138
  store i16 %add68, i16* %a.addr
  %140 = load i16, i16* %b.addr
  %141 = load i16, i16* %a.addr
  %add69 = add nsw i16 %141, %140
  store i16 %add69, i16* %a.addr
  %142 = load i16, i16* %b.addr
  %143 = load i16, i16* %a.addr
  %add70 = add nsw i16 %143, %142
  store i16 %add70, i16* %a.addr
  %144 = load i16, i16* %b.addr
  %145 = load i16, i16* %a.addr
  %add71 = add nsw i16 %145, %144
  store i16 %add71, i16* %a.addr
  %146 = load i16, i16* %b.addr
  %147 = load i16, i16* %a.addr
  %add72 = add nsw i16 %147, %146
  store i16 %add72, i16* %a.addr
  %148 = load i16, i16* %b.addr
  %149 = load i16, i16* %a.addr
  %add73 = add nsw i16 %149, %148
  store i16 %add73, i16* %a.addr
  %150 = load i16, i16* %b.addr
  %151 = load i16, i16* %a.addr
  %add74 = add nsw i16 %151, %150
  store i16 %add74, i16* %a.addr
  %152 = load i16, i16* %b.addr
  %153 = load i16, i16* %a.addr
  %add75 = add nsw i16 %153, %152
  store i16 %add75, i16* %a.addr
  %154 = load i16, i16* %b.addr
  %155 = load i16, i16* %a.addr
  %add76 = add nsw i16 %155, %154
  store i16 %add76, i16* %a.addr
  %156 = load i16, i16* %b.addr
  %157 = load i16, i16* %a.addr
  %add77 = add nsw i16 %157, %156
  store i16 %add77, i16* %a.addr
  %158 = load i16, i16* %b.addr
  %159 = load i16, i16* %a.addr
  %add78 = add nsw i16 %159, %158
  store i16 %add78, i16* %a.addr
  %160 = load i16, i16* %b.addr
  %161 = load i16, i16* %a.addr
  %add79 = add nsw i16 %161, %160
  store i16 %add79, i16* %a.addr
  %162 = load i16, i16* %b.addr
  %163 = load i16, i16* %a.addr
  %add80 = add nsw i16 %163, %162
  store i16 %add80, i16* %a.addr
  %164 = load i16, i16* %b.addr
  %165 = load i16, i16* %a.addr
  %add81 = add nsw i16 %165, %164
  store i16 %add81, i16* %a.addr
  %166 = load i16, i16* %b.addr
  %167 = load i16, i16* %a.addr
  %add82 = add nsw i16 %167, %166
  store i16 %add82, i16* %a.addr
  %168 = load i16, i16* %b.addr
  %169 = load i16, i16* %a.addr
  %add83 = add nsw i16 %169, %168
  store i16 %add83, i16* %a.addr
  %170 = load i16, i16* %b.addr
  %171 = load i16, i16* %a.addr
  %add84 = add nsw i16 %171, %170
  store i16 %add84, i16* %a.addr
  %172 = load i16, i16* %b.addr
  %173 = load i16, i16* %a.addr
  %add85 = add nsw i16 %173, %172
  store i16 %add85, i16* %a.addr
  %174 = load i16, i16* %b.addr
  %175 = load i16, i16* %a.addr
  %add86 = add nsw i16 %175, %174
  store i16 %add86, i16* %a.addr
  %176 = load i16, i16* %b.addr
  %177 = load i16, i16* %a.addr
  %add87 = add nsw i16 %177, %176
  store i16 %add87, i16* %a.addr
  %178 = load i16, i16* %b.addr
  %179 = load i16, i16* %a.addr
  %add88 = add nsw i16 %179, %178
  store i16 %add88, i16* %a.addr
  %180 = load i16, i16* %b.addr
  %181 = load i16, i16* %a.addr
  %add89 = add nsw i16 %181, %180
  store i16 %add89, i16* %a.addr
  %182 = load i16, i16* %b.addr
  %183 = load i16, i16* %a.addr
  %add90 = add nsw i16 %183, %182
  store i16 %add90, i16* %a.addr
  %184 = load i16, i16* %b.addr
  %185 = load i16, i16* %a.addr
  %add91 = add nsw i16 %185, %184
  store i16 %add91, i16* %a.addr
  %186 = load i16, i16* %b.addr
  %187 = load i16, i16* %a.addr
  %add92 = add nsw i16 %187, %186
  store i16 %add92, i16* %a.addr
  %188 = load i16, i16* %b.addr
  %189 = load i16, i16* %a.addr
  %add93 = add nsw i16 %189, %188
  store i16 %add93, i16* %a.addr
  %190 = load i16, i16* %b.addr
  %191 = load i16, i16* %a.addr
  %add94 = add nsw i16 %191, %190
  store i16 %add94, i16* %a.addr
  %192 = load i16, i16* %b.addr
  %193 = load i16, i16* %a.addr
  %add95 = add nsw i16 %193, %192
  store i16 %add95, i16* %a.addr
  %194 = load i16, i16* %b.addr
  %195 = load i16, i16* %a.addr
  %add96 = add nsw i16 %195, %194
  store i16 %add96, i16* %a.addr
  %196 = load i16, i16* %b.addr
  %197 = load i16, i16* %a.addr
  %add97 = add nsw i16 %197, %196
  store i16 %add97, i16* %a.addr
  %198 = load i16, i16* %b.addr
  %199 = load i16, i16* %a.addr
  %add98 = add nsw i16 %199, %198
  store i16 %add98, i16* %a.addr
  %200 = load i16, i16* %b.addr
  %201 = load i16, i16* %a.addr
  %add99 = add nsw i16 %201, %200
  store i16 %add99, i16* %a.addr
  %202 = load i16, i16* %b.addr
  %203 = load i16, i16* %a.addr
  %add100 = add nsw i16 %203, %202
  store i16 %add100, i16* %a.addr
  %204 = load i16, i16* %b.addr
  %205 = load i16, i16* %a.addr
  %add101 = add nsw i16 %205, %204
  store i16 %add101, i16* %a.addr
  %206 = load i16, i16* %b.addr
  %207 = load i16, i16* %a.addr
  %add102 = add nsw i16 %207, %206
  store i16 %add102, i16* %a.addr
  %208 = load i16, i16* %b.addr
  %209 = load i16, i16* %a.addr
  %add103 = add nsw i16 %209, %208
  store i16 %add103, i16* %a.addr
  %210 = load i16, i16* %b.addr
  %211 = load i16, i16* %a.addr
  %add104 = add nsw i16 %211, %210
  store i16 %add104, i16* %a.addr
  %212 = load i16, i16* %b.addr
  %213 = load i16, i16* %a.addr
  %add105 = add nsw i16 %213, %212
  store i16 %add105, i16* %a.addr
  %214 = load i16, i16* %b.addr
  %215 = load i16, i16* %a.addr
  %add106 = add nsw i16 %215, %214
  store i16 %add106, i16* %a.addr
  %216 = load i16, i16* %b.addr
  %217 = load i16, i16* %a.addr
  %add107 = add nsw i16 %217, %216
  store i16 %add107, i16* %a.addr
  %218 = load i16, i16* %b.addr
  %219 = load i16, i16* %a.addr
  %add108 = add nsw i16 %219, %218
  store i16 %add108, i16* %a.addr
  %220 = load i16, i16* %b.addr
  %221 = load i16, i16* %a.addr
  %add109 = add nsw i16 %221, %220
  store i16 %add109, i16* %a.addr
  %222 = load i16, i16* %b.addr
  %223 = load i16, i16* %a.addr
  %add110 = add nsw i16 %223, %222
  store i16 %add110, i16* %a.addr
  %224 = load i16, i16* %b.addr
  %225 = load i16, i16* %a.addr
  %add111 = add nsw i16 %225, %224
  store i16 %add111, i16* %a.addr
  %226 = load i16, i16* %b.addr
  %227 = load i16, i16* %a.addr
  %add112 = add nsw i16 %227, %226
  store i16 %add112, i16* %a.addr
  %228 = load i16, i16* %b.addr
  %229 = load i16, i16* %a.addr
  %add113 = add nsw i16 %229, %228
  store i16 %add113, i16* %a.addr
  %230 = load i16, i16* %b.addr
  %231 = load i16, i16* %a.addr
  %add114 = add nsw i16 %231, %230
  store i16 %add114, i16* %a.addr
  %232 = load i16, i16* %b.addr
  %233 = load i16, i16* %a.addr
  %add115 = add nsw i16 %233, %232
  store i16 %add115, i16* %a.addr
  %234 = load i16, i16* %b.addr
  %235 = load i16, i16* %a.addr
  %add116 = add nsw i16 %235, %234
  store i16 %add116, i16* %a.addr
  %236 = load i16, i16* %b.addr
  %237 = load i16, i16* %a.addr
  %add117 = add nsw i16 %237, %236
  store i16 %add117, i16* %a.addr
  %238 = load i16, i16* %b.addr
  %239 = load i16, i16* %a.addr
  %add118 = add nsw i16 %239, %238
  store i16 %add118, i16* %a.addr
  %240 = load i16, i16* %b.addr
  %241 = load i16, i16* %a.addr
  %add119 = add nsw i16 %241, %240
  store i16 %add119, i16* %a.addr
  %242 = load i16, i16* %b.addr
  %243 = load i16, i16* %a.addr
  %add120 = add nsw i16 %243, %242
  store i16 %add120, i16* %a.addr
  %244 = load i16, i16* %b.addr
  %245 = load i16, i16* %a.addr
  %add121 = add nsw i16 %245, %244
  store i16 %add121, i16* %a.addr
  %246 = load i16, i16* %b.addr
  %247 = load i16, i16* %a.addr
  %add122 = add nsw i16 %247, %246
  store i16 %add122, i16* %a.addr
  %248 = load i16, i16* %b.addr
  %249 = load i16, i16* %a.addr
  %add123 = add nsw i16 %249, %248
  store i16 %add123, i16* %a.addr
  %250 = load i16, i16* %b.addr
  %251 = load i16, i16* %a.addr
  %add124 = add nsw i16 %251, %250
  store i16 %add124, i16* %a.addr
  %252 = load i16, i16* %b.addr
  %253 = load i16, i16* %a.addr
  %add125 = add nsw i16 %253, %252
  store i16 %add125, i16* %a.addr
  %254 = load i16, i16* %b.addr
  %255 = load i16, i16* %a.addr
  %add126 = add nsw i16 %255, %254
  store i16 %add126, i16* %a.addr
  %256 = load i16, i16* %b.addr
  %257 = load i16, i16* %a.addr
  %add127 = add nsw i16 %257, %256
  store i16 %add127, i16* %a.addr
  %258 = load i16, i16* %b.addr
  %259 = load i16, i16* %a.addr
  %add128 = add nsw i16 %259, %258
  store i16 %add128, i16* %a.addr
  %260 = load i16, i16* %b.addr
  %261 = load i16, i16* %a.addr
  %add129 = add nsw i16 %261, %260
  store i16 %add129, i16* %a.addr
  %262 = load i16, i16* %b.addr
  %263 = load i16, i16* %a.addr
  %add130 = add nsw i16 %263, %262
  store i16 %add130, i16* %a.addr
  %264 = load i16, i16* %b.addr
  %265 = load i16, i16* %a.addr
  %add131 = add nsw i16 %265, %264
  store i16 %add131, i16* %a.addr
  %266 = load i16, i16* %b.addr
  %267 = load i16, i16* %a.addr
  %add132 = add nsw i16 %267, %266
  store i16 %add132, i16* %a.addr
  %268 = load i16, i16* %b.addr
  %269 = load i16, i16* %a.addr
  %add133 = add nsw i16 %269, %268
  store i16 %add133, i16* %a.addr
  %270 = load i16, i16* %b.addr
  %271 = load i16, i16* %a.addr
  %add134 = add nsw i16 %271, %270
  store i16 %add134, i16* %a.addr
  %272 = load i16, i16* %b.addr
  %273 = load i16, i16* %a.addr
  %add135 = add nsw i16 %273, %272
  store i16 %add135, i16* %a.addr
  %274 = load i16, i16* %b.addr
  %275 = load i16, i16* %a.addr
  %add136 = add nsw i16 %275, %274
  store i16 %add136, i16* %a.addr
  %276 = load i16, i16* %b.addr
  %277 = load i16, i16* %a.addr
  %add137 = add nsw i16 %277, %276
  store i16 %add137, i16* %a.addr
  %278 = load i16, i16* %b.addr
  %279 = load i16, i16* %a.addr
  %add138 = add nsw i16 %279, %278
  store i16 %add138, i16* %a.addr
  %280 = load i16, i16* %b.addr
  %281 = load i16, i16* %a.addr
  %add139 = add nsw i16 %281, %280
  store i16 %add139, i16* %a.addr
  %282 = load i16, i16* %b.addr
  %283 = load i16, i16* %a.addr
  %add140 = add nsw i16 %283, %282
  store i16 %add140, i16* %a.addr
  %284 = load i16, i16* %b.addr
  %285 = load i16, i16* %a.addr
  %add141 = add nsw i16 %285, %284
  store i16 %add141, i16* %a.addr
  %286 = load i16, i16* %b.addr
  %287 = load i16, i16* %a.addr
  %add142 = add nsw i16 %287, %286
  store i16 %add142, i16* %a.addr
  %288 = load i16, i16* %b.addr
  %289 = load i16, i16* %a.addr
  %add143 = add nsw i16 %289, %288
  store i16 %add143, i16* %a.addr
  %290 = load i16, i16* %b.addr
  %291 = load i16, i16* %a.addr
  %add144 = add nsw i16 %291, %290
  store i16 %add144, i16* %a.addr
  %292 = load i16, i16* %b.addr
  %293 = load i16, i16* %a.addr
  %add145 = add nsw i16 %293, %292
  store i16 %add145, i16* %a.addr
  %294 = load i16, i16* %b.addr
  %295 = load i16, i16* %a.addr
  %add146 = add nsw i16 %295, %294
  store i16 %add146, i16* %a.addr
  %296 = load i16, i16* %b.addr
  %297 = load i16, i16* %a.addr
  %add147 = add nsw i16 %297, %296
  store i16 %add147, i16* %a.addr
  %298 = load i16, i16* %b.addr
  %299 = load i16, i16* %a.addr
  %add148 = add nsw i16 %299, %298
  store i16 %add148, i16* %a.addr
  %300 = load i16, i16* %b.addr
  %301 = load i16, i16* %a.addr
  %add149 = add nsw i16 %301, %300
  store i16 %add149, i16* %a.addr
  %302 = load i16, i16* %b.addr
  %303 = load i16, i16* %a.addr
  %add150 = add nsw i16 %303, %302
  store i16 %add150, i16* %a.addr
  %304 = load i16, i16* %b.addr
  %305 = load i16, i16* %a.addr
  %add151 = add nsw i16 %305, %304
  store i16 %add151, i16* %a.addr
  %306 = load i16, i16* %b.addr
  %307 = load i16, i16* %a.addr
  %add152 = add nsw i16 %307, %306
  store i16 %add152, i16* %a.addr
  %308 = load i16, i16* %b.addr
  %309 = load i16, i16* %a.addr
  %add153 = add nsw i16 %309, %308
  store i16 %add153, i16* %a.addr
  %310 = load i16, i16* %b.addr
  %311 = load i16, i16* %a.addr
  %add154 = add nsw i16 %311, %310
  store i16 %add154, i16* %a.addr
  %312 = load i16, i16* %b.addr
  %313 = load i16, i16* %a.addr
  %add155 = add nsw i16 %313, %312
  store i16 %add155, i16* %a.addr
  %314 = load i16, i16* %b.addr
  %315 = load i16, i16* %a.addr
  %add156 = add nsw i16 %315, %314
  store i16 %add156, i16* %a.addr
  %316 = load i16, i16* %b.addr
  %317 = load i16, i16* %a.addr
  %add157 = add nsw i16 %317, %316
  store i16 %add157, i16* %a.addr
  %318 = load i16, i16* %b.addr
  %319 = load i16, i16* %a.addr
  %add158 = add nsw i16 %319, %318
  store i16 %add158, i16* %a.addr
  %320 = load i16, i16* %b.addr
  %321 = load i16, i16* %a.addr
  %add159 = add nsw i16 %321, %320
  store i16 %add159, i16* %a.addr
  %322 = load i16, i16* %b.addr
  %323 = load i16, i16* %a.addr
  %add160 = add nsw i16 %323, %322
  store i16 %add160, i16* %a.addr
  %324 = load i16, i16* %b.addr
  %325 = load i16, i16* %a.addr
  %add161 = add nsw i16 %325, %324
  store i16 %add161, i16* %a.addr
  %326 = load i16, i16* %b.addr
  %327 = load i16, i16* %a.addr
  %add162 = add nsw i16 %327, %326
  store i16 %add162, i16* %a.addr
  %328 = load i16, i16* %b.addr
  %329 = load i16, i16* %a.addr
  %add163 = add nsw i16 %329, %328
  store i16 %add163, i16* %a.addr
  %330 = load i16, i16* %b.addr
  %331 = load i16, i16* %a.addr
  %add164 = add nsw i16 %331, %330
  store i16 %add164, i16* %a.addr
  %332 = load i16, i16* %b.addr
  %333 = load i16, i16* %a.addr
  %add165 = add nsw i16 %333, %332
  store i16 %add165, i16* %a.addr
  %334 = load i16, i16* %b.addr
  %335 = load i16, i16* %a.addr
  %add166 = add nsw i16 %335, %334
  store i16 %add166, i16* %a.addr
  %336 = load i16, i16* %b.addr
  %337 = load i16, i16* %a.addr
  %add167 = add nsw i16 %337, %336
  store i16 %add167, i16* %a.addr
  %338 = load i16, i16* %b.addr
  %339 = load i16, i16* %a.addr
  %add168 = add nsw i16 %339, %338
  store i16 %add168, i16* %a.addr
  %340 = load i16, i16* %b.addr
  %341 = load i16, i16* %a.addr
  %add169 = add nsw i16 %341, %340
  store i16 %add169, i16* %a.addr
  %342 = load i16, i16* %b.addr
  %343 = load i16, i16* %a.addr
  %add170 = add nsw i16 %343, %342
  store i16 %add170, i16* %a.addr
  %344 = load i16, i16* %b.addr
  %345 = load i16, i16* %a.addr
  %add171 = add nsw i16 %345, %344
  store i16 %add171, i16* %a.addr
  %346 = load i16, i16* %b.addr
  %347 = load i16, i16* %a.addr
  %add172 = add nsw i16 %347, %346
  store i16 %add172, i16* %a.addr
  %348 = load i16, i16* %b.addr
  %349 = load i16, i16* %a.addr
  %add173 = add nsw i16 %349, %348
  store i16 %add173, i16* %a.addr
  %350 = load i16, i16* %b.addr
  %351 = load i16, i16* %a.addr
  %add174 = add nsw i16 %351, %350
  store i16 %add174, i16* %a.addr
  %352 = load i16, i16* %b.addr
  %353 = load i16, i16* %a.addr
  %add175 = add nsw i16 %353, %352
  store i16 %add175, i16* %a.addr
  %354 = load i16, i16* %b.addr
  %355 = load i16, i16* %a.addr
  %add176 = add nsw i16 %355, %354
  store i16 %add176, i16* %a.addr
  %356 = load i16, i16* %b.addr
  %357 = load i16, i16* %a.addr
  %add177 = add nsw i16 %357, %356
  store i16 %add177, i16* %a.addr
  %358 = load i16, i16* %b.addr
  %359 = load i16, i16* %a.addr
  %add178 = add nsw i16 %359, %358
  store i16 %add178, i16* %a.addr
  %360 = load i16, i16* %b.addr
  %361 = load i16, i16* %a.addr
  %add179 = add nsw i16 %361, %360
  store i16 %add179, i16* %a.addr
  %362 = load i16, i16* %b.addr
  %363 = load i16, i16* %a.addr
  %add180 = add nsw i16 %363, %362
  store i16 %add180, i16* %a.addr
  %364 = load i16, i16* %b.addr
  %365 = load i16, i16* %a.addr
  %add181 = add nsw i16 %365, %364
  store i16 %add181, i16* %a.addr
  %366 = load i16, i16* %b.addr
  %367 = load i16, i16* %a.addr
  %add182 = add nsw i16 %367, %366
  store i16 %add182, i16* %a.addr
  %368 = load i16, i16* %b.addr
  %369 = load i16, i16* %a.addr
  %add183 = add nsw i16 %369, %368
  store i16 %add183, i16* %a.addr
  %370 = load i16, i16* %b.addr
  %371 = load i16, i16* %a.addr
  %add184 = add nsw i16 %371, %370
  store i16 %add184, i16* %a.addr
  %372 = load i16, i16* %b.addr
  %373 = load i16, i16* %a.addr
  %add185 = add nsw i16 %373, %372
  store i16 %add185, i16* %a.addr
  %374 = load i16, i16* %b.addr
  %375 = load i16, i16* %a.addr
  %add186 = add nsw i16 %375, %374
  store i16 %add186, i16* %a.addr
  %376 = load i16, i16* %b.addr
  %377 = load i16, i16* %a.addr
  %add187 = add nsw i16 %377, %376
  store i16 %add187, i16* %a.addr
  %378 = load i16, i16* %b.addr
  %379 = load i16, i16* %a.addr
  %add188 = add nsw i16 %379, %378
  store i16 %add188, i16* %a.addr
  %380 = load i16, i16* %b.addr
  %381 = load i16, i16* %a.addr
  %add189 = add nsw i16 %381, %380
  store i16 %add189, i16* %a.addr
  %382 = load i16, i16* %b.addr
  %383 = load i16, i16* %a.addr
  %add190 = add nsw i16 %383, %382
  store i16 %add190, i16* %a.addr
  %384 = load i16, i16* %b.addr
  %385 = load i16, i16* %a.addr
  %add191 = add nsw i16 %385, %384
  store i16 %add191, i16* %a.addr
  %386 = load i16, i16* %b.addr
  %387 = load i16, i16* %a.addr
  %add192 = add nsw i16 %387, %386
  store i16 %add192, i16* %a.addr
  %388 = load i16, i16* %b.addr
  %389 = load i16, i16* %a.addr
  %add193 = add nsw i16 %389, %388
  store i16 %add193, i16* %a.addr
  %390 = load i16, i16* %b.addr
  %391 = load i16, i16* %a.addr
  %add194 = add nsw i16 %391, %390
  store i16 %add194, i16* %a.addr
  %392 = load i16, i16* %b.addr
  %393 = load i16, i16* %a.addr
  %add195 = add nsw i16 %393, %392
  store i16 %add195, i16* %a.addr
  %394 = load i16, i16* %b.addr
  %395 = load i16, i16* %a.addr
  %add196 = add nsw i16 %395, %394
  store i16 %add196, i16* %a.addr
  %396 = load i16, i16* %b.addr
  %397 = load i16, i16* %a.addr
  %add197 = add nsw i16 %397, %396
  store i16 %add197, i16* %a.addr
  %398 = load i16, i16* %b.addr
  %399 = load i16, i16* %a.addr
  %add198 = add nsw i16 %399, %398
  store i16 %add198, i16* %a.addr
  %400 = load i16, i16* %b.addr
  %401 = load i16, i16* %a.addr
  %add199 = add nsw i16 %401, %400
  store i16 %add199, i16* %a.addr
  %402 = load i16, i16* %b.addr
  %403 = load i16, i16* %a.addr
  %add200 = add nsw i16 %403, %402
  store i16 %add200, i16* %a.addr
  %404 = load i16, i16* %b.addr
  %405 = load i16, i16* %a.addr
  %add201 = add nsw i16 %405, %404
  store i16 %add201, i16* %a.addr
  %406 = load i16, i16* %b.addr
  %407 = load i16, i16* %a.addr
  %add202 = add nsw i16 %407, %406
  store i16 %add202, i16* %a.addr
  %408 = load i16, i16* %b.addr
  %409 = load i16, i16* %a.addr
  %add203 = add nsw i16 %409, %408
  store i16 %add203, i16* %a.addr
  %410 = load i16, i16* %b.addr
  %411 = load i16, i16* %a.addr
  %add204 = add nsw i16 %411, %410
  store i16 %add204, i16* %a.addr
  %412 = load i16, i16* %b.addr
  %413 = load i16, i16* %a.addr
  %add205 = add nsw i16 %413, %412
  store i16 %add205, i16* %a.addr
  %414 = load i16, i16* %b.addr
  %415 = load i16, i16* %a.addr
  %add206 = add nsw i16 %415, %414
  store i16 %add206, i16* %a.addr
  %416 = load i16, i16* %b.addr
  %417 = load i16, i16* %a.addr
  %add207 = add nsw i16 %417, %416
  store i16 %add207, i16* %a.addr
  %418 = load i16, i16* %b.addr
  %419 = load i16, i16* %a.addr
  %add208 = add nsw i16 %419, %418
  store i16 %add208, i16* %a.addr
  %420 = load i16, i16* %b.addr
  %421 = load i16, i16* %a.addr
  %add209 = add nsw i16 %421, %420
  store i16 %add209, i16* %a.addr
  %422 = load i16, i16* %b.addr
  %423 = load i16, i16* %a.addr
  %add210 = add nsw i16 %423, %422
  store i16 %add210, i16* %a.addr
  %424 = load i16, i16* %b.addr
  %425 = load i16, i16* %a.addr
  %add211 = add nsw i16 %425, %424
  store i16 %add211, i16* %a.addr
  br label %if.end

if.end:
  %426 = load i16, i16* %a.addr
  ret i16 %426
}
