; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV16K %s

declare i16 @external_function(i16)

define i16 @test_call_external(i16 %a) nounwind {
; RV16K-LABEL: test_call_external:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -2
; RV16K-NEXT:	swsp	ra, 0(sp)
; RV16K-NEXT:	jal	external_function
; RV16K-NEXT:	lwsp	ra, 0(sp)
; RV16K-NEXT:	addi	sp, 2
; RV16K-NEXT:	jr	ra

  %1 = call i16 @external_function(i16 %a)
  ret i16 %1
}

define i16 @defined_function(i16 %a) nounwind {
; RV16K-LABEL: defined_function:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	a0, 1
; RV16K-NEXT:	jr	ra
  %1 = add i16 %a, 1
  ret i16 %1
}

define i16 @test_call_defined(i16 %a) nounwind {
; RV16K-LABEL: test_call_defined:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -2
; RV16K-NEXT:	swsp	ra, 0(sp)
; RV16K-NEXT:	jal	defined_function
; RV16K-NEXT:	lwsp	ra, 0(sp)
; RV16K-NEXT:	addi	sp, 2
; RV16K-NEXT:	jr	ra
  %1 = call i16 @defined_function(i16 %a) nounwind
  ret i16 %1
}

define i16 @test_call_indirect(i16 (i16)* %a, i16 %b) nounwind {
; RV16K-LABEL: test_call_indirect:
; RV16K:       # %bb.0:
; RV16K-NEXT:   addi sp, -2
; RV16K-NEXT:	swsp	ra, 0(sp)
; RV16K-NEXT:	mov	a2, a0
; RV16K-NEXT:	mov	a0, a1
; RV16K-NEXT:	jalr	a2
; RV16K-NEXT:	lwsp	ra, 0(sp)
; RV16K-NEXT:	addi	sp, 2
; RV16K-NEXT:	jr	ra
  %1 = call i16 %a(i16 %b)
  ret i16 %1
}

declare i16 @external_many_args(i16, i16, i16, i16, i16, i16, i16, i16, i16, i16) nounwind

define i16 @test_call_external_many_args(i16 %a) nounwind {
; RV16K-LABEL: test_call_external_many_args:
; RV16K:       # %bb.0:
; RV16K-NEXT:	li	a1, 12
; RV16K-NEXT:	sub	sp, a1
; RV16K-NEXT:	swsp	ra, 10(sp)
; RV16K-NEXT:	swsp	s0, 8(sp)
; RV16K-NEXT:	mov	s0, a0
; RV16K-NEXT:	swsp	a0, 6(sp)
; RV16K-NEXT:	swsp	a0, 4(sp)
; RV16K-NEXT:	swsp	a0, 2(sp)
; RV16K-NEXT:	swsp	a0, 0(sp)
; RV16K-NEXT:	mov	a1, a0
; RV16K-NEXT:	mov	a2, a0
; RV16K-NEXT:	mov	a3, a0
; RV16K-NEXT:	mov	a4, a0
; RV16K-NEXT:	mov	a5, a0
; RV16K-NEXT:	jal	external_many_args
; RV16K-NEXT:	mov	a0, s0
; RV16K-NEXT:	lwsp	s0, 8(sp)
; RV16K-NEXT:	lwsp	ra, 10(sp)
; RV16K-NEXT:	li	a1, 12
; RV16K-NEXT:	add	sp, a1
; RV16K-NEXT:	jr	ra

  %1 = call i16 @external_many_args(i16 %a, i16 %a, i16 %a, i16 %a, i16 %a,
                                    i16 %a, i16 %a, i16 %a, i16 %a, i16 %a)
  ret i16 %a
}

define i16 @defined_many_args(i16, i16, i16, i16, i16, i16, i16, i16, i16, i16 %j) nounwind {
; RV16K-LABEL: defined_many_args:
; RV16K:       # %bb.0:
; RV16K-NEXT:	lwsp	a0, 6(sp)
; RV16K-NEXT:	addi	a0, 1
; RV16K-NEXT:	jr	ra
  %added = add i16 %j, 1
  ret i16 %added
}

define i16 @test_call_defined_many_args(i16 %a) nounwind {
; RV16K-LABEL: test_call_defined_many_args:
; RV16K:       # %bb.0:
; RV16K-NEXT:	li	a1, 10
; RV16K-NEXT:	sub	sp, a1
; RV16K-NEXT:	swsp	ra, 8(sp)
; RV16K-NEXT:	swsp	a0, 6(sp)
; RV16K-NEXT:	swsp	a0, 4(sp)
; RV16K-NEXT:	swsp	a0, 2(sp)
; RV16K-NEXT:	swsp	a0, 0(sp)
; RV16K-NEXT:	mov	a1, a0
; RV16K-NEXT:	mov	a2, a0
; RV16K-NEXT:	mov	a3, a0
; RV16K-NEXT:	mov	a4, a0
; RV16K-NEXT:	mov	a5, a0
; RV16K-NEXT:	jal	defined_many_args
; RV16K-NEXT:	lwsp	ra, 8(sp)
; RV16K-NEXT:	li	a1, 10
; RV16K-NEXT:	add	sp, a1
; RV16K-NEXT:	jr	ra

  %1 = call i16 @defined_many_args(i16 %a, i16 %a, i16 %a, i16 %a, i16 %a,
                                   i16 %a, i16 %a, i16 %a, i16 %a, i16 %a)
  ret i16 %1
}

; Ensure that calls to fastcc functions aren't rejected. Such calls may be
; introduced when compiling with optimisation.

define fastcc i16 @fastcc_function(i16 %a, i16 %b) nounwind {
; RV16K-LABEL: fastcc_function:
; RV16K:       # %bb.0:
; RV16K-NEXT:	add	a0, a1
; RV16K-NEXT:	jr	ra

 %1 = add i16 %a, %b
 ret i16 %1
}

define i16 @test_call_fastcc(i16 %a, i16 %b) nounwind {
; RV16K-LABEL: test_call_fastcc:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -4
; RV16K-NEXT:	swsp	ra, 2(sp)
; RV16K-NEXT:	swsp	s0, 0(sp)
; RV16K-NEXT:	mov	s0, a0
; RV16K-NEXT:	jal	fastcc_function
; RV16K-NEXT:	mov	a0, s0
; RV16K-NEXT:	lwsp	s0, 0(sp)
; RV16K-NEXT:	lwsp	ra, 2(sp)
; RV16K-NEXT:	addi	sp, 4
; RV16K-NEXT:	jr	ra

  %1 = call fastcc i16 @fastcc_function(i16 %a, i16 %b)
  ret i16 %a
}
