; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

declare i16 @bar(i16*, i16*)

define i16 @foo() {
; RV16K-LABEL: foo:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -6
; RV16K-NEXT:	swsp	ra, 4(sp)
; RV16K-NEXT:	li	a0, 2
; RV16K-NEXT:	add	a0, sp
; RV16K-NEXT:	mov	a1, sp
; RV16K-NEXT:	jal	bar
; RV16K-NEXT:	lwsp	ra, 4(sp)
; RV16K-NEXT:	addi	sp, 6
; RV16K-NEXT:	jr	ra

  %1 = alloca i16
  %2 = alloca i16
  %3 = call i16 @bar(i16* %1, i16 *%2)
  ret i16 %3
}
