; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

define i16 @indirectbr(i8* %target) nounwind {
; RV16K-LABEL: indirectbr:
; RV16K:       # %bb.0:
; RV16K-NEXT:	jr	a0
; RV16K-NEXT:.LBB0_1:
; RV16K-NEXT:	li	a0, 0
; RV16K-NEXT:	jr	ra

  indirectbr i8* %target, [label %test_label]
test_label:
  br label %ret
ret:
  ret i16 0
}

define i16 @indirectbr_with_offset(i8* %a) nounwind {
; RV16K-LABEL: indirectbr_with_offset:
; RV16K:       # %bb.0:
; RV16K-NEXT:	li	a1, 1380
; RV16K-NEXT:	add	a1, a0
; RV16K-NEXT:	jr	a1
; RV16K-NEXT:.LBB1_1:
; RV16K-NEXT:	li	a0, 0
; RV16K-NEXT:	jr	ra

  %target = getelementptr i8, i8* %a, i16 1380
  indirectbr i8* %target, [label %test_label]
test_label:
  br label %ret
ret:
  ret i16 0
}
