; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

define void @jt(i16 %in, i16* %out) {
; RV16K-LABEL: jt:
; RV16K:       # %bb.0: # %entry
; RV16K:	addi	sp, -2
; RV16K:	sw	fp, 0(sp)
; RV16K:	mov	fp, sp
; RV16K:	addi	fp, 2
; RV16K:	li	a2, 2
; RV16K:	cmp	a2, a0
; RV16K:	jl	.LBB0_3
; RV16K:	j	.LBB0_1
; RV16K:.LBB0_1:                                # %entry
; RV16K:	cmpi	a0, 1
; RV16K:	je	.LBB0_5
; RV16K:	j	.LBB0_2
; RV16K:.LBB0_2:                                # %entry
; RV16K:	cmpi	a0, 2
; RV16K:	je	.LBB0_6
; RV16K:	j	.LBB0_9
; RV16K:.LBB0_6:                                # %bb2
; RV16K:	li	a0, 3
; RV16K:	sw	a0, 0(a1)
; RV16K:	j	.LBB0_9
; RV16K:.LBB0_3:                                # %entry
; RV16K:	cmpi	a0, 3
; RV16K:	je	.LBB0_7
; RV16K:	j	.LBB0_4
; RV16K:.LBB0_4:                                # %entry
; RV16K:	cmpi	a0, 4
; RV16K:	je	.LBB0_8
; RV16K:	j	.LBB0_9
; RV16K:.LBB0_8:                                # %bb4
; RV16K:	li	a0, 1
; RV16K:	sw	a0, 0(a1)
; RV16K:.LBB0_9:                                # %exit
; RV16K:	lw	fp, 0(sp)
; RV16K:	addi	sp, 2
; RV16K:	jr	ra
; RV16K:.LBB0_5:                                # %bb1
; RV16K:	li	a0, 4
; RV16K:	sw	a0, 0(a1)
; RV16K:	j	.LBB0_9
; RV16K:.LBB0_7:                                # %bb3
; RV16K:	sw	a2, 0(a1)
; RV16K:	j	.LBB0_9

entry:
  switch i16 %in, label %exit [
    i16 1, label %bb1
    i16 2, label %bb2
    i16 3, label %bb3
    i16 4, label %bb4
  ]
bb1:
  store i16 4, i16* %out
  br label %exit
bb2:
  store i16 3, i16* %out
  br label %exit
bb3:
  store i16 2, i16* %out
  br label %exit
bb4:
  store i16 1, i16* %out
  br label %exit
exit:
  ret void
}
