; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

define void @jt(i16 %in, i16* %out) {
; RV16K-LABEL: jt:
; RV16K:       # %bb.0:
; RV16K-NEXT:	li	a2, 2
; RV16K-NEXT:	cmp	a2, a0
; RV16K-NEXT:	jl	.LBB0_4
; RV16K-NEXT:# %bb.1:
; RV16K-NEXT:	cmpi	a0, 1
; RV16K-NEXT:	je	.LBB0_7
; RV16K-NEXT:# %bb.2:
; RV16K-NEXT:	cmpi	a0, 2
; RV16K-NEXT:	jne	.LBB0_9
; RV16K-NEXT:# %bb.3:                                # %bb2
; RV16K-NEXT:	li	a0, 3
; RV16K-NEXT:	sw	a0, 0(a1)
; RV16K-NEXT:	jr	ra
; RV16K-NEXT:.LBB0_4:
; RV16K-NEXT:	cmpi	a0, 3
; RV16K-NEXT:	je	.LBB0_8
; RV16K-NEXT:# %bb.5:
; RV16K-NEXT:	cmpi	a0, 4
; RV16K-NEXT:	jne	.LBB0_9
; RV16K-NEXT:# %bb.6:                                # %bb4
; RV16K-NEXT:	li	a0, 1
; RV16K-NEXT:	sw	a0, 0(a1)
; RV16K-NEXT:	jr	ra
; RV16K-NEXT:.LBB0_7:                                # %bb1
; RV16K-NEXT:	li	a0, 4
; RV16K-NEXT:	sw	a0, 0(a1)
; RV16K-NEXT:	jr	ra
; RV16K-NEXT:.LBB0_8:                                # %bb3
; RV16K-NEXT:	sw	a2, 0(a1)
; RV16K-NEXT:.LBB0_9:                                # %exit
; RV16K-NEXT:	jr	ra

  switch i16 %in, label %exit [
    i16 1, label %bb1
    i16 2, label %bb2
    i16 3, label %bb3
    i16 4, label %bb4
  ]
bb1:
  store i16 4, i16* %out
  br label %exit
bb2:
  store i16 3, i16* %out
  br label %exit
bb3:
  store i16 2, i16* %out
  br label %exit
bb4:
  store i16 1, i16* %out
  br label %exit
exit:
  ret void
}
