; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV16K %s

; TODO: the quality of the generated code is poor

define void @test() nounwind {
; RV16K-LABEL: test:
; RV16K:       # %bb.0:
; RV16K-NEXT:	li	a0, 30002
; RV16K-NEXT:	sub	sp, a0
; RV16K-NEXT:	sw	fp, 30000(sp)
; RV16K-NEXT:	mov	fp, sp
; RV16K-NEXT:	li	a0, 30002
; RV16K-NEXT:	add	fp, a0
; RV16K-NEXT:	lw	fp, 30000(sp)
; RV16K-NEXT:	li	a0, 30002
; RV16K-NEXT:	add	sp, a0
; RV16K-NEXT:	jr	ra

  %tmp = alloca [ 30000 x i8 ] , align 2
  ret void
}
