; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV16K-FPELIM %s
; RUN: llc -mtriple=rv16k -verify-machineinstrs -frame-pointer=all < %s \
; RUN:   | FileCheck -check-prefix=RV16K-WITHFP %s

; TODO: the quality of the generated code is poor

define void @test() nounwind {
; RV16K-WITHFP-LABEL: test:
; RV16K-WITHFP:       # %bb.0:
; RV16K-WITHFP-NEXT:	li	a0, 30004
; RV16K-WITHFP-NEXT:	sub	sp, a0
; RV16K-WITHFP-NEXT:	sw	ra, 30002(sp)
; RV16K-WITHFP-NEXT:	sw	fp, 30000(sp)
; RV16K-WITHFP-NEXT:	mov	fp, sp
; RV16K-WITHFP-NEXT:	li	a0, 30004
; RV16K-WITHFP-NEXT:	add	fp, a0
; RV16K-WITHFP-NEXT:	lw	fp, 30000(sp)
; RV16K-WITHFP-NEXT:	lw	ra, 30002(sp)
; RV16K-WITHFP-NEXT:	li	a0, 30004
; RV16K-WITHFP-NEXT:	add	sp, a0
; RV16K-WITHFP-NEXT:	jr	ra

; RV16K-FPELIM-LABEL: test:
; RV16K-FPELIM:       # %bb.0:
; RV16K-FPELIM-NEXT:	li	a0, 30000
; RV16K-FPELIM-NEXT:	sub	sp, a0
; RV16K-FPELIM-NEXT:	li	a0, 30000
; RV16K-FPELIM-NEXT:	add	sp, a0
; RV16K-FPELIM-NEXT:	jr	ra

  %tmp = alloca [ 30000 x i8 ] , align 2
  ret void
}
