; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=rv16k -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV16K

define i16 @urem(i16 %a, i16 %b) nounwind {
; RV16K-LABEL: urem:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -2
; RV16K-NEXT:	swsp	ra, 0(sp)
; RV16K-NEXT:	jal	__umodhi3
; RV16K-NEXT:	lwsp	ra, 0(sp)
; RV16K-NEXT:	addi	sp, 2
; RV16K-NEXT:	jr	ra

  %1 = urem i16 %a, %b
  ret i16 %1
}

define i16 @srem(i16 %a, i16 %b) nounwind {
; RV16K-LABEL: srem:
; RV16K:       # %bb.0:
; RV16K-NEXT:	addi	sp, -2
; RV16K-NEXT:	swsp	ra, 0(sp)
; RV16K-NEXT:	jal	__modhi3
; RV16K-NEXT:	lwsp	ra, 0(sp)
; RV16K-NEXT:	addi	sp, 2
; RV16K-NEXT:	jr	ra

  %1 = srem i16 %a, %b
  ret i16 %1
}
